# Generated by Django 3.2.13 on 2022-05-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[ #우리가 만들지 않은 것! # id - 숫자하나씩 증가, 이게 primary key foriegn key로 됨. 자동생성. 숫자.ㅐ
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('url', models.URLField(verbose_name='Site URL')),
            ],
        ),
    ]

#기능 만들고 확인 너무 오래걸림 -> 장고에는 이미 관리자 페이지라는 기능이 있음. 원하는대로 만들어져있는지 확인!